### PR TITLE
add mc formatting code sanitization

### PR DESCRIPTION
**Pull request by ImVaskel**
This adds minecraft formatting codes sanitizing (if they are valid).

### CODE REVIEW

**Comment by acuifex** [comment]
matches invalid formatting codes like `HIJPQ`

**Comment by ImVaskel** [comment]
capitals are supported, and while those are matched, there is no point to over-complicate the regex to include 5 characters that get accidentally matched.

**Comment by acuifex** [comment]
`§§aa` will be replaced to `§a`
just replace the `§` character with `&` or something, like i told.

**Comment by TraceLD** [comment]
Implemented already by 0e9cf2bbd229a79cb9103dab21697204391b8be0

**Pull request closed without merging**
